import 'package:flutter/material.dart';

const colors = [
    Colors.pink,
    Colors.pink,
    Colors.pink,
    Colors.purple,
    Color.fromARGB(255, 25, 25, 25),
    Color.fromARGB(255, 25, 25, 25),
    Color.fromARGB(255, 25, 25, 25),
    Colors.purple,
    Color.fromARGB(255, 25, 25, 25),
    Color.fromARGB(255, 25, 25, 25),
    Color.fromARGB(255, 25, 25, 25),
    Colors.purple,
    Color.fromARGB(255, 25, 25, 25),
    Color.fromARGB(255, 25, 25, 25),
    Color.fromARGB(255, 25, 25, 25),
    Colors.purple,
    Color.fromARGB(255, 25, 25, 25),
    Color.fromARGB(255, 25, 25, 25),
    Color.fromARGB(255, 25, 25, 25),
    Colors.purple,
];

const controllers = [
    Text("AC", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("()", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("%", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("÷", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("7", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("8", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("9", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("X", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("4", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("5", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("6", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("-", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("1", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("2", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("3", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text("+", style: TextStyle(color: Colors.white, fontSize: 28)),
    Text(".", style: TextStyle(color: Colors.white, fontSize: 20)),
    Text("0", style: TextStyle(color: Colors.white, fontSize: 20)),
    Icon(Icons.backspace_rounded, color: Colors.white),
    Text("=", style: TextStyle(color: Colors.white, fontSize: 20)),
];